In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [112]:
df = pd.read_csv('adult.csv')

In [113]:
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [114]:
df.describe()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [116]:
df.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [117]:
df_enc = df.copy()

In [118]:
df_enc = df_enc.drop('fnlwgt', axis=1)

In [119]:
df_enc['workclass'].value_counts()

workclass
Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [120]:
df_enc['workclass'] = df_enc['workclass'].replace('?', df_enc['workclass'].mode()[0])

In [121]:
df_enc['workclass'].value_counts()

workclass
Private             24532
Self-emp-not-inc     2541
Local-gov            2093
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [122]:
df_enc = df_enc.drop('education', axis=1)

In [123]:
df_enc['marital.status'].value_counts()

marital.status
Married-civ-spouse       14976
Never-married            10683
Divorced                  4443
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64

In [124]:
df_enc['occupation'].value_counts()

occupation
Prof-specialty       4140
Craft-repair         4099
Exec-managerial      4066
Adm-clerical         3770
Sales                3650
Other-service        3295
Machine-op-inspct    2002
?                    1843
Transport-moving     1597
Handlers-cleaners    1370
Farming-fishing       994
Tech-support          928
Protective-serv       649
Priv-house-serv       149
Armed-Forces            9
Name: count, dtype: int64

In [125]:
df_enc['occupation'] = df_enc['occupation'].replace('?', df_enc['occupation'].mode()[0])

In [126]:
df_enc['relationship'].value_counts()

relationship
Husband           13193
Not-in-family      8305
Own-child          5068
Unmarried          3446
Wife               1568
Other-relative      981
Name: count, dtype: int64

In [127]:
df_enc['race'].value_counts()

race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

In [128]:
df_enc['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

In [129]:
df_enc['capital.gain'] = np.log1p(df_enc['capital.gain'])

In [130]:
df_enc['capital.loss'] = np.log1p(df_enc['capital.loss'])

In [131]:
from sklearn.preprocessing import StandardScaler

In [133]:
scaler = StandardScaler()

df_enc['hours.per.week'] = scaler.fit_transform(df_enc[['hours.per.week']])
df_enc['education.num'] = scaler.fit_transform(df_enc[['education.num']])
df_enc['age'] = scaler.fit_transform(df_enc[['age']])

In [134]:
df_enc['native.country'].value_counts()

native.country
United-States                 29170
Mexico                          643
?                               583
Philippines                     198
Germany                         137
Canada                          121
Puerto-Rico                     114
El-Salvador                     106
India                           100
Cuba                             95
England                          90
Jamaica                          81
South                            80
China                            75
Italy                            73
Dominican-Republic               70
Vietnam                          67
Guatemala                        64
Japan                            62
Poland                           60
Columbia                         59
Taiwan                           51
Haiti                            44
Iran                             43
Portugal                         37
Nicaragua                        34
Peru                             31
Greece                           29
France                           29
Ecuador                          28
Ireland                          24
Hong                             20
Trinadad&Tobago                  19
Cambodia                         19
Thailand                         18
Laos                             18
Yugoslavia                       16
Outlying-US(Guam-USVI-etc)       14
Hungary                          13
Honduras                         13
Scotland                         12
Holand-Netherlands                1
Name: count, dtype: int64

In [135]:
df_enc['native.country'] = df_enc['native.country'].replace('?', 'Other')

In [136]:
df_enc['native.country'].value_counts().head()

native.country
United-States    29170
Mexico             643
Other              583
Philippines        198
Germany            137
Name: count, dtype: int64

In [137]:
df_enc['income'].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [138]:
df_enc['income'] = df_enc['income'].map({'<=50K': 0, '>50K': 1})

In [139]:
df_enc['income'].value_counts()

income
0    24720
1     7841
Name: count, dtype: int64

In [140]:
import category_encoders as ce

In [141]:
cat_columns = ['workclass', 'marital.status', 'occupation', 'relationship', 'race', 'sex', 'native.country']

In [142]:
df_enc.head()

,age,workclass,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,3.769612,Private,-0.420060,Widowed,Prof-specialty,Not-in-family,White,Female,0.0,8.379539,-0.035429,United-States,0
1,3.183112,Private,-0.420060,Widowed,Exec-managerial,Not-in-family,White,Female,0.0,8.379539,-1.817204,United-States,0
2,2.010110,Private,-0.031360,Widowed,Prof-specialty,Unmarried,Black,Female,0.0,8.379539,-0.035429,United-States,0
3,1.130359,Private,-2.363558,Divorced,Machine-op-inspct,Unmarried,White,Female,0.0,8.268988,-0.035429,United-States,0
4,0.177296,Private,-0.031360,Separated,Prof-specialty,Own-child,White,Female,0.0,8.268988,-0.035429,United-States,0

In [143]:
X = df_enc.drop('income', axis=1)
y = df_enc['income']
X.shape, y.shape

((32561, 12), (32561,))

In [144]:
encoder = ce.TargetEncoder(cols=cat_columns, smoothing=10)

In [145]:
df_enc_xgb = encoder.fit_transform(X, y)

In [166]:
df_enc_xgb['income'] = y

In [168]:
df_enc_xgb.head()

,age,workclass,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,3.769612,0.210093,-0.420060,0.085599,0.342637,0.103070,0.25586,0.109461,0.0,8.379539,-0.035429,0.245835,0
1,3.183112,0.210093,-0.420060,0.085599,0.484014,0.103070,0.25586,0.109461,0.0,8.379539,-1.817204,0.245835,0
2,2.010110,0.210093,-0.031360,0.085599,0.342637,0.063262,0.12388,0.109461,0.0,8.379539,-0.035429,0.245835,0
3,1.130359,0.210093,-2.363558,0.104209,0.124875,0.063262,0.25586,0.109461,0.0,8.268988,-0.035429,0.245835,0
4,0.177296,0.210093,-0.031360,0.064390,0.342637,0.013220,0.25586,0.109461,0.0,8.268988,-0.035429,0.245835,0

In [169]:
df_enc_xgb.to_csv('df_enc_xgb.csv', index=False)

#### Dataset preprocession for CatBoost

In [148]:
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [149]:
df_cat = df.copy()

In [151]:
df_cat['workclass'] = df_cat['workclass'].replace('?', df_cat['workclass'].mode()[0])

In [152]:
df_cat = df_cat.drop(['fnlwgt', 'education.num'], axis=1)

In [156]:
df_cat['occupation'] = df_cat['occupation'].replace('?', df_cat['occupation'].mode()[0])

In [159]:
df_cat['native.country'] = df_cat['native.country'].replace('?', 'Other')

In [161]:
df_cat['capital.gain'] = np.log1p(df_cat['capital.gain'])

In [162]:
df_cat['capital.loss'] = np.log1p(df_cat['capital.loss'])

In [163]:
df_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   education       32561 non-null  object
 3   marital.status  32561 non-null  object
 4   occupation      32561 non-null  object
 5   relationship    32561 non-null  object
 6   race            32561 non-null  object
 7   sex             32561 non-null  object
 8   capital.gain    32561 non-null  float64
 9   capital.loss    32561 non-null  float64
 10  hours.per.week  32561 non-null  int64
 11  native.country  32561 non-null  object
 12  income          32561 non-null  object
dtypes: float64(2), int64(2), object(9)
memory usage: 3.2+ MB

In [164]:
df_cat.head()

,age,workclass,education,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,Private,HS-grad,Widowed,Prof-specialty,Not-in-family,White,Female,0.0,8.379539,40,United-States,<=50K
1,82,Private,HS-grad,Widowed,Exec-managerial,Not-in-family,White,Female,0.0,8.379539,18,United-States,<=50K
2,66,Private,Some-college,Widowed,Prof-specialty,Unmarried,Black,Female,0.0,8.379539,40,United-States,<=50K
3,54,Private,7th-8th,Divorced,Machine-op-inspct,Unmarried,White,Female,0.0,8.268988,40,United-States,<=50K
4,41,Private,Some-college,Separated,Prof-specialty,Own-child,White,Female,0.0,8.268988,40,United-States,<=50K

In [165]:
df_cat.to_csv('df_cat.csv', index=False)